export enum COURSE_ACTIONS {
    LOAD_COURSES = 'LOAD',
    STORE_COURSES = 'STORE_COURSES',
    FAILED_LOAD = 'FAILED_LOAD',
    DELETE_COURSE = 'DELETE_COURSE',
    PATCH_COURSE = 'PATCH_COURSE',
    ADD_COURSE = 'ADD_COURSE',
    FETCH_AUTHORS = 'FETCH_AUTHORS',
    STORE_AUTHORS = 'STORE_AUTHORS',
    LOAD_BY_ID_COURSE = 'LOAD_BY_ID_COURSE',
    STORE_COURSE = 'STORE_COURSE'
}